"""CDL emitter.

One .SUBCKT per module of the resolved design, in source order:

    .SUBCKT top a b y
    *.PININFO a:I b:I y:O
    Xu1 a b y NAND2
    .ENDS top

Instance names get the X prefix that SPICE requires for subcircuit calls.
Library cells are referenced, never copied: the comparator reads the library
CDL alongside this file. There are no timestamps, so two runs on the same
input produce the same bytes and can be diffed.
"""

from __future__ import annotations

from typing import TextIO

from .. import __version__
from ..errors import Location, OutputError
from ..model import ResolvedDesign
from .flavors import Flavor

_PININFO = {"input": "I", "output": "O", "inout": "B"}
_WIDTH = 80  # longer statements are wrapped with '+' continuation lines


def write_cdl(
    design: ResolvedDesign, flavor: Flavor, out: TextIO, source: str | None = None
) -> None:
    out.write(f"* Generated by v2c {__version__}\n")
    if source:
        out.write(f"* Source: {source}\n")
    out.write(f"* Top:    {design.top}\n")
    out.write(f"* Flavor: {flavor.name}\n")

    for module in design.modules:
        loc = module.location
        name = _name(module.name, loc)
        pins = [_name(pin, loc) for pin in module.pins]
        out.write("\n")
        _statement(out, [".SUBCKT", name, *pins])
        if flavor.emit_pininfo and pins:
            info = " ".join(
                f"{cdl}:{_PININFO[module.directions[pin]]}"
                for pin, cdl in zip(module.pins, pins)
            )
            out.write(f"*.PININFO {info}\n")
        for inst in module.instances:
            loc = inst.location
            _statement(
                out,
                ["X" + _name(inst.name, loc), *(_name(n, loc) for n in inst.nets),
                 _name(inst.cell, loc)],
            )
        out.write(f".ENDS {name}\n")


def _name(name: str, location: Location | None) -> str:
    # Escaped identifiers need a per-flavor rewrite policy (docs/flavors.md).
    if name.startswith("\\"):
        raise OutputError(f"escaped identifier '{name}': not supported yet", location)
    return name


def _statement(out: TextIO, words: list[str]) -> None:
    line = words[0]
    for word in words[1:]:
        if len(line) + 1 + len(word) > _WIDTH:
            out.write(line + "\n")
            line = "+ " + word
        else:
            line += " " + word
    out.write(line + "\n")
