import dataclasses
import io

import pytest

from v2c import __version__
from v2c.cdl.flavors import CALIBRE
from v2c.cdl.writer import write_cdl
from v2c.errors import Location, OutputError
from v2c.model import ResolvedDesign, ResolvedInstance, ResolvedModule


def design(*instances: ResolvedInstance, pins=("a", "y")) -> ResolvedDesign:
    directions = {"a": "input", "y": "output", "io": "inout"}
    module = ResolvedModule("top", list(pins), {p: directions[p] for p in pins},
                            list(instances), Location("t.v", 1))
    return ResolvedDesign("top", [module])


def write(d: ResolvedDesign, flavor=CALIBRE, source=None, includes=()) -> str:
    out = io.StringIO()
    write_cdl(d, flavor, out, source=source, includes=includes)
    return out.getvalue()


def test_output_shape():
    text = write(design(ResolvedInstance("u1", "INV", ["a", "y"]), pins=("a", "y", "io")),
                 source="t.v")
    assert text == (
        f"* Generated by v2c {__version__}\n"
        "* Source: t.v\n"
        "* Top:    top\n"
        "* Flavor: calibre\n"
        "\n"
        ".SUBCKT top a y io\n"
        "*.PININFO a:I y:O io:B\n"
        "Xu1 a y INV\n"
        ".ENDS top\n"
    )


def test_includes_come_before_the_first_subckt():
    text = write(design(), includes=["all.cdl", "/pdk/macros.cdl"])
    assert '\n\n.INCLUDE "all.cdl"\n.INCLUDE "/pdk/macros.cdl"\n\n.SUBCKT top' in text


def test_long_statements_wrap_with_continuation_lines():
    nets = [f"net_{i:03d}" for i in range(20)]
    text = write(design(ResolvedInstance("u1", "BIG", nets)))
    lines = text.splitlines()
    start = lines.index("Xu1 net_000 net_001 net_002 net_003 net_004 net_005 net_006 net_007 net_008")
    assert lines[start + 1].startswith("+ net_009 ")
    assert lines[start + 2].endswith(" net_019 BIG")
    assert all(len(line) <= 80 for line in lines)
    joined = " ".join(line.removeprefix("+ ") for line in lines[start:start + 3])
    assert joined.split() == ["Xu1", *nets, "BIG"]


def test_pininfo_follows_the_flavor():
    text = write(design(), flavor=dataclasses.replace(CALIBRE, emit_pininfo=False))
    assert "*.PININFO" not in text


def test_escaped_identifiers_are_rejected_until_they_have_a_policy():
    inst = ResolvedInstance("u1", "INV", [r"\a/b", "y"], Location("t.v", 7, 3))
    with pytest.raises(OutputError) as exc:
        write(design(inst))
    assert str(exc.value) == r"t.v:7:3: escaped identifier '\a/b': not supported yet"
